[Feat] #3 온보딩 및 로그인 UI 구현
Leets-Official/carrot-FE pull request #6
Opened 2024-10-09 05:10 UTC by odukong

## 1. 무슨 이유로 코드를 변경했나요?
- 당근알바 온보딩 UI 구현
- 로그인 UI 구현
- 로그인(이메일 인증 및 인증 번호 확인) 기본 코드 작성

## 2. 어떤 위험이나 장애를 발견했나요?
로컬 서버는 정상 작동하나 브라우저 무한로딩만 걸리고 화면이 보이지 않는 문제 발생.
[vite] error while updating dependencies: error: eperm: operation not permitted
⬆️ 장시간 로딩 후, 터미널에 뜬 에러 메시지

=> 아직 미해결..

## 3. 관련 스크린샷을 첨부해주세요.

https://github.com/user-attachments/assets/43e59442-7ac4-498d-b18a-0c21e0122571

+ 디자인적인 부분 수정 예정

## 4. 완료 사항
- 온보딩 UI 구현 완료 (+추가적인 디자인 수정은 O)
- 기본 로그인 기능 구현 완료

## 5. 추가 사항
- 모바일 화면크기 디자인 설정 수정
- 온보딩 UI 및 로그인 UI 디자인 수정 예정
- 토큰과 관련 로그인 추가 코드는 백엔드와 상의 후, 작성 예정

p.s. 브라우저가 안 보이는 상태(화면 확인 불가..)로 구현하였기에 추가적인 기능 구현과 수정이 어려워 다소 미흡한 코드가 된 점.. 양해 부탁드리겠습니다...🥺 (현재 로딩 문제가 해결되면 수정할 예정)

2024-10-09 06:16 UTC, One-HyeWon requested changes

2024-10-09 06:16 UTC, One-HyeWon commented on src/components/Button.jsx
> +  padding: 20px 30px;
padding도 %로 관리 하면, 화면 사이즈에 따라서 유연하게 변할 수 있어서 px 단위 보다는 %, vw, vh 와 같은 비율 단위를 사용하시는 걸 추천드립니다!

2024-10-09 06:16 UTC, One-HyeWon commented on src/styles/Landing.css
styled-component를 사용 하실 거라면, 현재 파일과 같은 css 파일 사용은 지양해주세요!
하나의 스타일 기법으로 통일하시는 걸 추천드립니다!

2024-10-09 06:16 UTC, One-HyeWon commented on src/pages/Landing.jsx
> +            navigate("./signup");
경로들이 전부 상대 경로인데, 절대 경로로 사용하지 않으신 이유가 있나요?

2024-10-09 06:16 UTC, One-HyeWon commented on src/pages/Landing.jsx
> +          color="#ff8a3d"
color들의 경우 같은 색상이 여러번 사용된다면 theme에서 관리하셔도 좋을 것 같아요!

2024-10-09 06:16 UTC, One-HyeWon commented on src/pages/Landing.jsx
> +          </span>
로그인은 Button 컴포넌트가 아닌 span 태그를 사용하신 이유가 있으실까요?
onClick 이벤트가 필요한 요소라면 Button 컴포넌트를 사용하시는 걸 권장드립니다!

2024-10-09 06:16 UTC, One-HyeWon commented on src/pages/register/Login.jsx
> +`;
styled-component가 너무 많아지면 아래 로직을 확인 하는데 어려움이 있으니, styles 파일에 Login.styles.js 파일을 만들어서 스타일 컴포넌트들을 컴포넌트 별로 관리하시는 걸 추천드립니다!

2024-10-09 06:16 UTC, One-HyeWon commented on src/pages/register/Login.jsx
> +  const [emailAuth, setEmailAuth] = useState(-1); //Email 인증 코드 일치 여부 (-1: 초기 설정 / 0: 인증 실패 / 1: 인증 확인 api 대기 / 2: 인증 성공)
상태변수가 너무 많아서 useState문이 길어지는 것은 직관적이지 않고, 헷갈릴 것 같아요!

```
const [emailState, setEmailState] = useState({
  email: "",
  emailAuthCode: "",
  emailValid: -1,
  emailRequest: -1,
  emailAuth: -1
});

const handleChangeEmail = (e) => {
  const input = e.target.value;
  setEmailState((prev) => ({
    ...prev,
    email: input,
    emailValid: validateEmail(input) ? 1 : 0,
    emailRequest: -1,
    emailAuth: -1
  }));
};
```

이메일 관련 변수들을 한 컴포넌트 안에서 관리를 하고 있는 중이니 하나의 객체로 상태 관리를 해도 좋을 것 같습니다!

2024-10-09 06:16 UTC, One-HyeWon commented on src/pages/register/Login.jsx
> +  };
상태를 숫자로 직접 사용하기 보다는 위에 상수를 선언해주어서 사용하는 것은 어떨까요?
더 안정적이고, 직관적일 수 있을 것 같아요!

```
const EMAIL_VALIDITY = {
  INITIAL: -1,
  INVALID: 0,
  VALID: 1
};

const EMAIL_REQUEST_STATUS = {
  NOT_REQUESTED: -1,
  FAILED: 0,
  PENDING: 1,
  SUCCESS: 2
};

const handleChangeEmail = (e) => {
  const input = e.target.value;
  setEmail(input);
  setEmailValid(validateEmail(input) ? EMAIL_VALIDITY.VALID : EMAIL_VALIDITY.INVALID);
};
```

2024-10-09 06:16 UTC, One-HyeWon commented on src/pages/register/Login.jsx
> +            disabled={emailRequest === 1 || 2}
의도 하셨던 부분은 emailRequest 가 1 혹은 2일때 true가 돼서 disabled 되게 하고 싶은게 맞으신가요?

제가 말씀드린 대로 상수로 관리를 하게 된다면
아래와 같은 코드로 수정 하면 더 안정적일 것 같습니다!

```
disabled={emailRequest === EMAIL_REQUEST_STATUS.PENDING || emailRequest === EMAIL_REQUEST_STATUS.SUCCESS}
```

2024-10-09 06:16 UTC, One-HyeWon commented on src/pages/register/Login.jsx
> +  };
```
  const validateEmail = (email) => {
    const emailtest = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailtest.test(email) ? EMAIL_VALIDITY.VALID : EMAIL_VALIDITY.INVALID;
  };
```

여기 return도 마찬가지로 상수로 관리하면 좋을 것 같습니다

2024-10-09 06:17 UTC, One-HyeWon commented
그리고 혹시 무한 로딩 되면서 화면 렌더 안 되는 문제 해결 하셨나요?

```
rm -rf node_modules
rm -f package-lock.json
npm cache clean --force
npm install
```

이렇게 캐시 지워도 안 되시면 혹시 VSCode 자체를 관리자 권한으로 실행 해보실래요?

2024-10-09 06:18 UTC, yezzan9 commented
제가 클론받아서 실행해보니 잘 되는 것 같아요!
node_modules 파일 삭제 후 다시 install 하거나, 클론을 새로 받아오면 해결되지 않을까요?!🥺

https://github.com/user-attachments/assets/1a6f1ddb-0271-43b3-8718-9dd4d41c895b

2024-10-09 06:41 UTC, odukong commented on src/components/Button.jsx
> +  padding: 20px 30px;
% 단위로 변경하도록 하겠습니다!

2024-10-09 06:45 UTC, odukong commented on src/pages/Landing.jsx
> +            navigate("./signup");
상대경로를 의도하고 작성한 코드가 아니라 절대경로로 수정하도록하겠습니당

2024-10-09 06:49 UTC, odukong commented on src/pages/Landing.jsx
> +          </span>
Button 컴포넌트를 사용하기엔 글씨 자체에만 클릭 이벤트가 들어가는 디자인 요소라 통일적인 면이 아닌 것 같아 간단히 span태그를 사용하였는데, span태그 대신 button 태그로 대체하여 수정하였습니다.

2024-10-09 06:56 UTC, odukong commented on src/pages/register/Login.jsx
> +`;
해당 방식으로 수정하였습니다 !

2024-10-09 07:05 UTC, odukong commented on src/pages/Landing.jsx
> +          color="#ff8a3d"
자주 사용될 메인 컬러들은 theme.js 파일 별도로 생성하여 관리할 수 있도록 수정하였습니다!

2024-10-09 07:13 UTC, One-HyeWon commented
현재 UI 만 구현이 되어 있는데, 아직 로그인 로직은 구현이 안 되어 있는 거죠?

2024-10-09 08:03 UTC, odukong commented on src/pages/register/Login.jsx
> +  };
이메일 형식, 인증 번호 useState 상태 변수 -1,0,1,2 모두 추천하신 방식대로 수정완료하였습니다!

2024-10-09 08:17 UTC, odukong commented
캐시파일 삭제 + node_modules 삭제 후, 재설치 + 관리자 권한으로 실행하였을 때도 동일한 문제가 계속 발생하더라구요.. 🥺

토큰 관련한 로그인 로직을 말씀하시는 거라면 아직 구현이 되지 않은 것이 맞습니다! 
지금 제대로 실행이 되지 않은 오류가 존재하여ㅠ 별도 util로 빼내어 axios 로직을 커스텀하려고 하던 계획이었는데 현재 상태로  남은 시간 안에 완전한 로직을 구현하기엔 무리라고 생각이 들어 기본적인 코드만 작성한 상태입니다..

2024-10-09 08:31 UTC, yezzan9 commented
@odukong 
> 캐시파일 삭제 + node_modules 삭제 후, 재설치 + 관리자 권한으로 실행하였을 때도 동일한 문제가 계속 발생하더라구요.. 🥺

아예 프로젝트 파일을 삭제하고 클론을 다시 받아도 안되나요?🥺

2024-10-09 08:43 UTC, odukong commented
@yezzan9 
> 
> > 캐시파일 삭제 + node_modules 삭제 후, 재설치 + 관리자 권한으로 실행하였을 때도 동일한 문제가 계속 발생하더라구요.. 🥺
> 
> 아예 프로젝트 파일을 삭제하고 클론을 다시 받아도 안되나요?🥺

방금 아예 삭제하고 클론 받아와서 다시 해봤는데 로컬 서버는 정상적으로 실행되는게 맞는데 브라우저 상에서는 무한 로딩되는 문제가 계속 되네요.. 😭

2024-10-09 08:58 UTC, minseoKim-11 reviewed
확인하였습니다. theme.js 파일에 명시된 색상 참고하겠습니다.

2024-10-13 13:32 UTC, One-HyeWon approved these changes
수정사항 반영 확인 했습니다!

2024-10-14 06:25 UTC, merged